name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_BlinkingLedAsm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ls
      run:  ls
    - name: Change dir to BlinkingLedAsm
      run:  cd BlinkingLedAsm
    - name: ls
      run:  ls      
    - name: make all
      run: make all
      
  Build_BlinkingLedC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Change dir to BlinkingLedC
      run:  cd BlinkingLedC
    - name: make all
      run: make all
